### ISSUE TITLE
Advantage over using goto-bus-stop/setup-zig?

### ISSUE THREAD

**Issue by linusg** [mlugg/setup-zig#4]
I'm not asking this in bad faith, I just saw a lot of activity around this new GitHub action and am curious why you made it / what the problems with the existing one are. Thanks!

**Comment by mlugg** [comment]
No problem! This action has a few benefits over the other one:
* It's actively maintained. @goto-bus-stop [has said](https://github.com/goto-bus-stop/setup-zig/issues/72#issuecomment-2078822121) they don't really have time to maintain her action. This one should receive more attention, since I'm an active community member. (No shade to goto-bus-stop here; she made something that has worked for a long time and I totally understand not having time to maintain it!)
* AFAICT, this action handles caching correctly, which goto-bus-stop's action [has had issues with](https://github.com/goto-bus-stop/setup-zig/issues/72).
* On cache misses, this action uses mirrors to download Zig rather than the official website, which is important to avoid unnecessary load on the ZSF servers, which today cost a good chunk of money to host due to high usage.
* This action caches your global cache directory (`~/.cache/zig`) between CI runs, which will speed up runs, potentially very significantly if e.g. your project has external dependencies which your `build.zig` builds. All local cache dirs are redirected to the global cache to make this caching more useful.
* This action verifies the minisign signature of the downloaded tarball, sidestepping issues if the ZSF servers (or any mirrors) are ever compromised.
* This action allows directly referencing [Mach nominated Zig versions](https://machengine.org/about/nominated-zig/), which some parts of the ecosystem are moving towards.

**Comment by linusg** [comment]
Thanks for the detailed answer, I have a few repos to update then 😄

**Comment by judofyr** [comment]
@mlugg: How about putting this information in the README? I also had the same question when finding this project.
